version: '3'

services:
  illusion:
    build: ./
    volumes:
      - ./share:/home/Illusion:ro
      - ./xinetd:/etc/xinetd.d/illusion:ro
    ports:
      - "10104:10101"
    expose:
      - "10101"
