version: '3'

services:
  guardian:
    build: .
    volumes:
      - ./share/:/home/guardian/:ro
      - ./init:/init:ro
      - ./xinetd:/etc/xinetd.d/guardian:ro
    ports:
      - "10101:10101"
    expose:
      - "10101"
    privileged: true
    restart: always
